apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
name: component-sample
description: Full blown sample yaml file that describes about the component
domain: Realestate
status: Approved
createddate: 07-15-2021
annotations:
backstage.io/techdocs-ref: url:https://github.com/chennas/gwc139
tags:
- java
- javascript
spec:
type: service
lifecycle: development
owner: team-a
secondaryonwer: siva
system: sample system
subcomponentOf: artist-lookup
providesApis: [spotify]
consumesApis: [starwars-graphql]
dependsOn: ["component:CBRE-1-order", "resource:artists-db"]
