apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www.preprodconfig-2.com
  description: preprodconfig-2 XYZ Service
spec:
  type: MicroService
  lifecycle: Development
  owner: preprodconfig-2 Team A
  system: preprodconfig-2 System A
