apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prod-api
  description: prod-api
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: podcast
