apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-templates-remote
  description: A collection of remotely available Backstage example templates
spec:
  type: url
  targets:
    - https://github.com/chennas/gwc139/blob/development/docs-template/template.yaml
