apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-cbre-new
  description: Team CBRE new
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-cbre@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-cbre@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
